### ISSUE TITLE
protect the item

### ISSUE THREAD

**Issue by TaeoG** [MelanX/Maledicta#3]
### Describe your idea

I have been unable to successfully de-curse a book, as the lightning sets it on fire and completely destroys it, even from a few blocks away. Could we maybe have it so items in an adjacent chest or something get de-cursed? So we can keep the items safe (and don't have to stand around in the rain staring at it and continually placing it back down so it doesn't despawn)

**Comment by MelanX** [comment]
Did you activate the safe lightnings? But no, I don't like the idea with the chest. It doesn't fit in the mod in my opinion. But thanks for the idea :)
